
build:
  image: golang:1.5
  environment:
    - GOPATH=/drone
  commands:
    - go get ./...
    - go test ./...

publish:
  docker:
    username: drone
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: drone/drone-exec
    when:
      branch: master
